
title: 'Portfolio'

baseurl: '/reginald-e-roberts.github.io' #change it according to your repository name



# Profile information
yourname: Reginald Eric Roberts  ## put your name
title: 'Computational Social Scientist'  ## your title
location: Culver City , CA


## Profiles

linkedin: https://www.linkedin.com/in/reginald-r-38abb03/  ## your linkedin account url





# Update all the sections by editing the files inside _includes folder.
